apiVersion: apps/v1
kind: Deployment
metadata:
  name: django-tic-tac-toe-deployment
  namespace: django-tic-tac-toe-ns
  labels:
    app: tic-tac-toe
spec:
  replicas: 1
  selector:
    matchLabels:
      app: tic-tac-toe
  template:
    metadata:
      labels:
        app: tic-tac-toe
    spec:
      containers:
        - name: django-tic-tac-toe
          image: 235130525963.dkr.ecr.ap-south-1.amazonaws.com/cicd-test/django-app:IMAGE_TAG_PLACEHOLDER
          ports:
            - containerPort: 8000