apiVersion: v1
kind: Service
metadata:
  name: django-tic-tac-toe-service
  namespace: django-tic-tac-toe-ns
spec:
  type: LoadBalancer
  selector:
    app: tic-tac-toe
  ports:
    - protocol: TCP
      port: 80
      targetPort: 8000