name: Django App CICD EKS

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Set up Python 3.11
      uses: actions/setup-python@v5
      with:
        python-version: '3.11'

    - name: Install Dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt

    - name: Run Tests
      run: |
        cd main
        python manage.py test

  build:
    needs: test
    runs-on: ubuntu-latest
    
    permissions:
      id-token: write
      contents: read

    steps:
    - name: Checkout code
      uses: actions/checkout@v4
      
    - name: Build Docker Image and Tag
      run: |  
        docker build -t django-app .
        docker tag django-app:latest 235130525963.dkr.ecr.ap-south-1.amazonaws.com/cicd-test/django-app:${{ github.sha }}
        docker tag django-app:latest 235130525963.dkr.ecr.ap-south-1.amazonaws.com/cicd-test/django-app:latest

    - name: Configure AWS Credentials
      uses: aws-actions/configure-aws-credentials@v4
      with:
        role-to-assume: arn:aws:iam::235130525963:role/oidc-iam-first-demo
        aws-region: ap-south-1

    - name: Login to ECR
      run: |
        aws ecr get-login-password --region ap-south-1 | docker login --username AWS --password-stdin 235130525963.dkr.ecr.ap-south-1.amazonaws.com

    - name: Push Docker Image to ECR
      run: |
        docker push 235130525963.dkr.ecr.ap-south-1.amazonaws.com/cicd-test/django-app:${{ github.sha }}
        docker push 235130525963.dkr.ecr.ap-south-1.amazonaws.com/cicd-test/django-app:latest

  deploy:
      needs: build
      runs-on: ubuntu-latest
      

      permissions:
        id-token: write
        contents: read

      steps: 
      - name: Checkout code
        uses: actions/checkout@v4

  
      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
          role-to-assume: arn:aws:iam::235130525963:role/oidc-iam-first-demo 
          aws-region: ap-south-1

      - name: Update deployment file with new image tag
        run: |
          sed -i "s/IMAGE_TAG_PLACEHOLDER/${{ github.sha }}/g" kind/deployment.yml

      - name: Update kubeconfig and create resources
        run: |
          aws eks update-kubeconfig --region ap-south-1 --name my-eks-cluster
          kubectl apply -f kind/namespace.yml
          kubectl apply -f kind/deployment.yml
          kubectl apply -f kind/service.yml
